/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'MyFlutterApp';

  //digits
  static const IconData six = IconData(0xe909, fontFamily: _kFontFam);
  static const IconData four = IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData fourteen = IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData nine = IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData one = IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData seven = IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData sixteen = IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData fifteen = IconData(0xe910, fontFamily: _kFontFam);
  static const IconData five = IconData(0xe911, fontFamily: _kFontFam);
  static const IconData eleven = IconData(0xe912, fontFamily: _kFontFam);
  static const IconData eight = IconData(0xe913, fontFamily: _kFontFam);
  static const IconData ten = IconData(0xe914, fontFamily: _kFontFam);
  static const IconData thirteen = IconData(0xe915, fontFamily: _kFontFam);
  static const IconData three = IconData(0xe916, fontFamily: _kFontFam);
  static const IconData twelve = IconData(0xe917, fontFamily: _kFontFam);
  static const IconData two = IconData(0xe918, fontFamily: _kFontFam);
  
  // custom logo
  static const IconData nfc = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData vuejs = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData yeslogo_2 = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData yeslogoonly = IconData(0xe803, fontFamily: _kFontFam);
  
  // programmings
  static const IconData language_java = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData language_python = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData dartlang = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData flutter_seeklogo_com = IconData(0xe80b, fontFamily: _kFontFam);
  
  //social media
  static const IconData line_icon = IconData(0xe908, fontFamily: _kFontFam);
  static const IconData twitter = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData blogger = IconData(0xe807, fontFamily: _kFontFam);


  static const IconData ac_unit = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData access_alarms = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData access_time = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData account_balance = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData account_balance_wallet = const IconData(0xf008, fontFamily: _kFontFam);
  static const IconData account_circle = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData adb = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData add_a_photo = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData add_circle_outline = const IconData(0xe91b, fontFamily: _kFontFam);
  static const IconData add_to_photos = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData airplanemode_active = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData airplanemode_inactive = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData alarm = const IconData(0xe91c, fontFamily: _kFontFam);
  static const IconData alarm_off = const IconData(0xe91d, fontFamily: _kFontFam);
  static const IconData all_inclusive = const IconData(0xe91e, fontFamily: _kFontFam);
  static const IconData android = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData apple = const IconData(0xf179, fontFamily: _kFontFam);
  static const IconData apps = const IconData(0xe91f, fontFamily: _kFontFam);
  static const IconData archive = const IconData(0xe940, fontFamily: _kFontFam);
  static const IconData arrow_combo = const IconData(0xe8f1, fontFamily: _kFontFam);
  static const IconData arrow_downward = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData arrow_drop_down = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData arrow_drop_down_circle = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData arrow_drop_up = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData arrow_forward = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData arrows_ccw = const IconData(0xe943, fontFamily: _kFontFam);
  static const IconData arrows_cw = const IconData(0xe904, fontFamily: _kFontFam);
  static const IconData aspect_ratio = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData assignment_ind = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData attach = const IconData(0xe8cd, fontFamily: _kFontFam);
  static const IconData attach_1 = const IconData(0xe8e3, fontFamily: _kFontFam);
  static const IconData backup = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData battery_0 = const IconData(0xf244, fontFamily: _kFontFam);
  static const IconData battery_1 = const IconData(0xf243, fontFamily: _kFontFam);
  static const IconData battery_2 = const IconData(0xf242, fontFamily: _kFontFam);
  static const IconData battery_3 = const IconData(0xf241, fontFamily: _kFontFam);
  static const IconData battery_4 = const IconData(0xf240, fontFamily: _kFontFam);
  static const IconData battery_alert = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData battery_charging_full = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData beaker = const IconData(0xf0c3, fontFamily: _kFontFam);
  static const IconData beenhere = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData behance_squared = const IconData(0xf1b5, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe937, fontFamily: _kFontFam);
  static const IconData bluetooth_audio = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData bluetooth_connected = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData bluetooth_disabled = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe93c, fontFamily: _kFontFam);
  static const IconData border_color = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData box = const IconData(0xe941, fontFamily: _kFontFam);
  static const IconData branding_watermark = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData brightness_4 = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData brightness_5 = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData brightness_6 = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData brightness_auto = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData brightness_high = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData brightness_medium = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData brush = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData brush_1 = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData bug_report = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData build = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData business_center = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData cached = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData call_merge = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData call_split = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe8dc, fontFamily: _kFontFam);
  static const IconData cancel_circle = const IconData(0xe8de, fontFamily: _kFontFam);
  static const IconData cart_arrow_down = const IconData(0xf218, fontFamily: _kFontFam);
  static const IconData cast = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData cast_connected = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData chart_line = const IconData(0xf201, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData chat_1 = const IconData(0xe8d1, fontFamily: _kFontFam);
  static const IconData chat_bubble = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData chat_empty = const IconData(0xf0e6, fontFamily: _kFontFam);
  static const IconData check_circle = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData child = const IconData(0xf1ae, fontFamily: _kFontFam);
  static const IconData chrome = const IconData(0xe8c8, fontFamily: _kFontFam);
  static const IconData chrome_1 = const IconData(0xf268, fontFamily: _kFontFam);
  static const IconData cloud_done = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData cloud_download = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData cloud_thunder = const IconData(0xe952, fontFamily: _kFontFam);
  static const IconData cloud_upload = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData code = const IconData(0xe920, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData cog_alt = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData collections = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData collections_bookmark = const IconData(0xe922, fontFamily: _kFontFam);
  static const IconData color_lens = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData colorize = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe8d0, fontFamily: _kFontFam);
  static const IconData comment_empty = const IconData(0xf0e5, fontFamily: _kFontFam);
  static const IconData commenting = const IconData(0xf27a, fontFamily: _kFontFam);
  static const IconData commenting_o = const IconData(0xf27b, fontFamily: _kFontFam);
  static const IconData compare_arrows = const IconData(0xe921, fontFamily: _kFontFam);
  static const IconData computer = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData content_copy = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData content_cut = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData control_point = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData control_point_duplicate = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData create = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData crop_free = const IconData(0xe923, fontFamily: _kFontFam);
  static const IconData cube = const IconData(0xf1b2, fontFamily: _kFontFam);
  static const IconData cup = const IconData(0xe93a, fontFamily: _kFontFam);
  static const IconData cw = const IconData(0xe8fa, fontFamily: _kFontFam);
  static const IconData cw_1 = const IconData(0xe942, fontFamily: _kFontFam);
  static const IconData d3_rotation = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData database = const IconData(0xf1c0, fontFamily: _kFontFam);
  static const IconData dehaze = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData delicious = const IconData(0xf1a5, fontFamily: _kFontFam);
  static const IconData dialpad = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData digg = const IconData(0xf1a6, fontFamily: _kFontFam);
  static const IconData direction = const IconData(0xf124, fontFamily: _kFontFam);
  static const IconData directions = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData do_not_disturb = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData doc_text = const IconData(0xe93e, fontFamily: _kFontFam);
  static const IconData doc_text_inv = const IconData(0xe93d, fontFamily: _kFontFam);
  static const IconData done = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData done_all = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData donut_small = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData dot_3 = const IconData(0xe951, fontFamily: _kFontFam);
  static const IconData down_circle = const IconData(0xe8fb, fontFamily: _kFontFam);
  static const IconData down_circle_1 = const IconData(0xe8ff, fontFamily: _kFontFam);
  static const IconData down_circled2 = const IconData(0xe8ef, fontFamily: _kFontFam);
  static const IconData down_dir = const IconData(0xe8ee, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe933, fontFamily: _kFontFam);
  static const IconData download_1 = const IconData(0xe962, fontFamily: _kFontFam);
  static const IconData download_cloud = const IconData(0xf0ed, fontFamily: _kFontFam);
  static const IconData drafts = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData dropbox = const IconData(0xf16b, fontFamily: _kFontFam);
  static const IconData drupal = const IconData(0xf1a9, fontFamily: _kFontFam);
  static const IconData dvr = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe8cf, fontFamily: _kFontFam);
  static const IconData edit_1 = const IconData(0xe95b, fontFamily: _kFontFam);
  static const IconData eject = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData enhanced_encryption = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData euro_symbol = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData event = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData event_available = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData event_busy = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData exchange = const IconData(0xe8f7, fontFamily: _kFontFam);
  static const IconData export_1 = const IconData(0xe95f, fontFamily: _kFontFam);
  static const IconData export_alt = const IconData(0xf14d, fontFamily: _kFontFam);
  static const IconData export_icon = const IconData(0xe8d2, fontFamily: _kFontFam);
  static const IconData extension = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData face = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData facebook_squared = const IconData(0xf308, fontFamily: _kFontFam);
  static const IconData favorite = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData favorite_border = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData feather = const IconData(0xe939, fontFamily: _kFontFam);
  static const IconData file_download = const IconData(0xe961, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData filter_list = const IconData(0xe861, fontFamily: _kFontFam);
  static const IconData find_replace = const IconData(0xe862, fontFamily: _kFontFam);
  static const IconData fingerprint = const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData fire = const IconData(0xe8d9, fontFamily: _kFontFam);
  static const IconData firefox = const IconData(0xf269, fontFamily: _kFontFam);
  static const IconData flash_auto = const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData flash_off = const IconData(0xe865, fontFamily: _kFontFam);
  static const IconData flash_on = const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData floppy = const IconData(0xe934, fontFamily: _kFontFam);
  static const IconData floppy_1 = const IconData(0xe958, fontFamily: _kFontFam);
  static const IconData flow_branch = const IconData(0xe954, fontFamily: _kFontFam);
  static const IconData flow_cascade = const IconData(0xe953, fontFamily: _kFontFam);
  static const IconData flow_line = const IconData(0xe956, fontFamily: _kFontFam);
  static const IconData flow_parallel = const IconData(0xe957, fontFamily: _kFontFam);
  static const IconData flow_tree = const IconData(0xe955, fontFamily: _kFontFam);
  static const IconData folder = const IconData(0xe93f, fontFamily: _kFontFam);
  static const IconData folder_open = const IconData(0xe8d3, fontFamily: _kFontFam);
  static const IconData fork = const IconData(0xf126, fontFamily: _kFontFam);
  static const IconData format_color_fill = const IconData(0xe867, fontFamily: _kFontFam);
  static const IconData format_color_reset = const IconData(0xe868, fontFamily: _kFontFam);
  static const IconData format_color_text = const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData format_indent_decrease = const IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData format_indent_increase = const IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData forumbee = const IconData(0xf211, fontFamily: _kFontFam);
  static const IconData forward = const IconData(0xe92f, fontFamily: _kFontFam);
  static const IconData forward_5 = const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData forward_10 = const IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData forward_30 = const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData gg = const IconData(0xf260, fontFamily: _kFontFam);
  static const IconData gg_circle = const IconData(0xf261, fontFamily: _kFontFam);
  static const IconData git = const IconData(0xf1d3, fontFamily: _kFontFam);
  static const IconData git_squared = const IconData(0xf1d2, fontFamily: _kFontFam);
  static const IconData github = const IconData(0xf113, fontFamily: _kFontFam);
  static const IconData github_circled = const IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData goat = const IconData(0xe871, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam);
  static const IconData gplus = const IconData(0xf0d5, fontFamily: _kFontFam);
  static const IconData gps_fixed = const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData gps_not_fixed = const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe872, fontFamily: _kFontFam);
  static const IconData group_add = const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData hand_grab_o = const IconData(0xf255, fontFamily: _kFontFam);
  static const IconData hand_paper_o = const IconData(0xf256, fontFamily: _kFontFam);
  static const IconData hand_pointer_o = const IconData(0xf25a, fontFamily: _kFontFam);
  static const IconData hdr_off = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData hdr_on = const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData headphones = const IconData(0xe8d5, fontFamily: _kFontFam);
  static const IconData headset = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData headset_mic = const IconData(0xe877, fontFamily: _kFontFam);
  static const IconData hearing = const IconData(0xe878, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe8e0, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe8e1, fontFamily: _kFontFam);
  static const IconData help_outline = const IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData highlight_off = const IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData hourglass = const IconData(0xf254, fontFamily: _kFontFam);
  static const IconData hourglass_1 = const IconData(0xf251, fontFamily: _kFontFam);
  static const IconData hourglass_2 = const IconData(0xf252, fontFamily: _kFontFam);
  static const IconData hourglass_3 = const IconData(0xf253, fontFamily: _kFontFam);
  static const IconData hourglass_empty = const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData hourglass_full = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData hourglass_o = const IconData(0xf250, fontFamily: _kFontFam);
  static const IconData id_icon = const IconData(0xe907, fontFamily: _kFontFam);
  static const IconData ie = const IconData(0xe8c9, fontFamily: _kFontFam);
  static const IconData important_devices = const IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData industrial_building = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData insert_chart = const IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData internet_explorer = const IconData(0xf26b, fontFamily: _kFontFam);
  static const IconData invert_colors = const IconData(0xe880, fontFamily: _kFontFam);
  static const IconData invert_colors_off = const IconData(0xe881, fontFamily: _kFontFam);
  static const IconData iso = const IconData(0xe882, fontFamily: _kFontFam);
  static const IconData jsfiddle = const IconData(0xf1cc, fontFamily: _kFontFam);
  static const IconData key = const IconData(0xe8da, fontFamily: _kFontFam);
  static const IconData language = const IconData(0xf1ab, fontFamily: _kFontFam);
  static const IconData language_html5 = const IconData(0xe8e9, fontFamily: _kFontFam);
  static const IconData language_javascript__1_ = const IconData(0xe8e6, fontFamily: _kFontFam);
  static const IconData launch = const IconData(0xe883, fontFamily: _kFontFam);
  static const IconData layers = const IconData(0xe884, fontFamily: _kFontFam);
  static const IconData layers_clear = const IconData(0xe885, fontFamily: _kFontFam);
  static const IconData leak_add = const IconData(0xe886, fontFamily: _kFontFam);
  static const IconData leak_remove = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData left_circle = const IconData(0xe8fc, fontFamily: _kFontFam);
  static const IconData left_circle_1 = const IconData(0xe900, fontFamily: _kFontFam);
  static const IconData left_circled2 = const IconData(0xf190, fontFamily: _kFontFam);
  static const IconData left_dir = const IconData(0xe8eb, fontFamily: _kFontFam);
  static const IconData left_open = const IconData(0xe8f3, fontFamily: _kFontFam);
  static const IconData left_open_outline = const IconData(0xe8f2, fontFamily: _kFontFam);
  static const IconData level_down = const IconData(0xe944, fontFamily: _kFontFam);
  static const IconData level_up = const IconData(0xe945, fontFamily: _kFontFam);
  static const IconData library_books = const IconData(0xe889, fontFamily: _kFontFam);
  static const IconData library_music = const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData lightbulb = const IconData(0xe8e8, fontFamily: _kFontFam);
  static const IconData lightbulb_alt = const IconData(0xe8e7, fontFamily: _kFontFam);
  static const IconData lightbulb_outline = const IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData link = const IconData(0xe8ce, fontFamily: _kFontFam);
  static const IconData link_1 = const IconData(0xf07b, fontFamily: _kFontFam);
  static const IconData link_2 = const IconData(0xe936, fontFamily: _kFontFam);
  static const IconData link_3 = const IconData(0xe960, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xf0e1, fontFamily: _kFontFam);
  static const IconData local_pharmacy = const IconData(0xe965, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe8e4, fontFamily: _kFontFam);
  static const IconData lock_empty = const IconData(0xe8e5, fontFamily: _kFontFam);
  static const IconData lock_open = const IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData lock_outline = const IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData loop = const IconData(0xe8f9, fontFamily: _kFontFam);
  static const IconData loop_1 = const IconData(0xe947, fontFamily: _kFontFam);
  static const IconData loop_alt = const IconData(0xe8f8, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe88b, fontFamily: _kFontFam);
  static const IconData mail_1 = const IconData(0xe935, fontFamily: _kFontFam);
  static const IconData mail_2 = const IconData(0xe959, fontFamily: _kFontFam);
  static const IconData mail_outline = const IconData(0xe88e, fontFamily: _kFontFam);
  static const IconData nature_people = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData network_check = const IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData notifications = const IconData(0xe890, fontFamily: _kFontFam);
  static const IconData notifications_active = const IconData(0xe891, fontFamily: _kFontFam);
  static const IconData notifications_none = const IconData(0xe892, fontFamily: _kFontFam);
  static const IconData notifications_off = const IconData(0xe893, fontFamily: _kFontFam);
  static const IconData notifications_paused = const IconData(0xe894, fontFamily: _kFontFam);
  static const IconData offline_pin = const IconData(0xe895, fontFamily: _kFontFam);
  static const IconData ok = const IconData(0xe8db, fontFamily: _kFontFam);
  static const IconData ok_circle = const IconData(0xe8dd, fontFamily: _kFontFam);
  static const IconData opacity = const IconData(0xe896, fontFamily: _kFontFam);
  static const IconData open_with = const IconData(0xe898, fontFamily: _kFontFam);
  static const IconData opera = const IconData(0xf26a, fontFamily: _kFontFam);
  static const IconData pages = const IconData(0xe897, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xe94b, fontFamily: _kFontFam);
  static const IconData paw = const IconData(0xf1b0, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe938, fontFamily: _kFontFam);
  static const IconData pencil_1 = const IconData(0xe95c, fontFamily: _kFontFam);
  static const IconData pencil_alt = const IconData(0xe95a, fontFamily: _kFontFam);
  static const IconData people = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData phone_android = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData phone_bluetooth_speaker = const IconData(0xe89d, fontFamily: _kFontFam);
  static const IconData phone_forwarded = const IconData(0xe89e, fontFamily: _kFontFam);
  static const IconData phone_in_talk = const IconData(0xe89f, fontFamily: _kFontFam);
  static const IconData phonelink_erase = const IconData(0xe89c, fontFamily: _kFontFam);
  static const IconData phonelink_lock = const IconData(0xe89b, fontFamily: _kFontFam);
  static const IconData phonelink_ring = const IconData(0xe89a, fontFamily: _kFontFam);
  static const IconData phonelink_setup = const IconData(0xe899, fontFamily: _kFontFam);
  static const IconData photo_filter = const IconData(0xe924, fontFamily: _kFontFam);
  static const IconData pinterest = const IconData(0xf231, fontFamily: _kFontFam);
  static const IconData pinterest_circled = const IconData(0xf0d2, fontFamily: _kFontFam);
  static const IconData pinterest_squared = const IconData(0xf0d3, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe949, fontFamily: _kFontFam);
  static const IconData play_arrow = const IconData(0xe8a5, fontFamily: _kFontFam);
  static const IconData play_circle_filled = const IconData(0xe8a4, fontFamily: _kFontFam);
  static const IconData play_circle_outline = const IconData(0xe8a3, fontFamily: _kFontFam);
  static const IconData playlist_add = const IconData(0xe8a0, fontFamily: _kFontFam);
  static const IconData playlist_add_check = const IconData(0xe8a1, fontFamily: _kFontFam);
  static const IconData playlist_play = const IconData(0xe8a2, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe8df, fontFamily: _kFontFam);
  static const IconData power_settings_new = const IconData(0xe8a6, fontFamily: _kFontFam);
  static const IconData product_hunt = const IconData(0xf288, fontFamily: _kFontFam);
  static const IconData programming_icon = const IconData(0xe905, fontFamily: _kFontFam);
  static const IconData progress_1 = const IconData(0xe94d, fontFamily: _kFontFam);
  static const IconData progress_2 = const IconData(0xe94f, fontFamily: _kFontFam);
  static const IconData progress_3 = const IconData(0xe94e, fontFamily: _kFontFam);
  static const IconData queue_music = const IconData(0xe8a7, fontFamily: _kFontFam);
  static const IconData quote_left = const IconData(0xf10d, fontFamily: _kFontFam);
  static const IconData quote_right = const IconData(0xf10e, fontFamily: _kFontFam);
  static const IconData record = const IconData(0xe94c, fontFamily: _kFontFam);
  static const IconData recycle = const IconData(0xf1b8, fontFamily: _kFontFam);
  static const IconData reddit = const IconData(0xf1a1, fontFamily: _kFontFam);
  static const IconData reddit_squared = const IconData(0xf1a2, fontFamily: _kFontFam);
  static const IconData renren = const IconData(0xf18b, fontFamily: _kFontFam);
  static const IconData repeat = const IconData(0xe8a9, fontFamily: _kFontFam);
  static const IconData repeat_one = const IconData(0xe8a8, fontFamily: _kFontFam);
  static const IconData replay = const IconData(0xe8ac, fontFamily: _kFontFam);
  static const IconData reply = const IconData(0xe8aa, fontFamily: _kFontFam);
  static const IconData reply_1 = const IconData(0xf112, fontFamily: _kFontFam);
  static const IconData reply_all = const IconData(0xe8ab, fontFamily: _kFontFam);
  static const IconData right_circle = const IconData(0xe8fd, fontFamily: _kFontFam);
  static const IconData right_circle_1 = const IconData(0xe901, fontFamily: _kFontFam);
  static const IconData right_circled2 = const IconData(0xf18e, fontFamily: _kFontFam);
  static const IconData right_dir = const IconData(0xe8ec, fontFamily: _kFontFam);
  static const IconData right_open = const IconData(0xe8f5, fontFamily: _kFontFam);
  static const IconData right_open_outline = const IconData(0xe8f4, fontFamily: _kFontFam);
  static const IconData rocket = const IconData(0xf135, fontFamily: _kFontFam);
  static const IconData rotate_left = const IconData(0xe8ad, fontFamily: _kFontFam);
  static const IconData rotate_right = const IconData(0xe8ae, fontFamily: _kFontFam);
  static const IconData rss = const IconData(0xf09e, fontFamily: _kFontFam);
  static const IconData rss_feed = const IconData(0xe8af, fontFamily: _kFontFam);
  static const IconData rss_squared = const IconData(0xf143, fontFamily: _kFontFam);
  static const IconData safari = const IconData(0xf267, fontFamily: _kFontFam);
  static const IconData save = const IconData(0xe8b1, fontFamily: _kFontFam);
  static const IconData school = const IconData(0xe8b0, fontFamily: _kFontFam);
  static const IconData sd_storage = const IconData(0xe8b3, fontFamily: _kFontFam);
  static const IconData settings_bluetooth = const IconData(0xe8b2, fontFamily: _kFontFam);
  static const IconData settings_ethernet = const IconData(0xe925, fontFamily: _kFontFam);
  static const IconData settings_input_antenna = const IconData(0xe927, fontFamily: _kFontFam);
  static const IconData settings_input_component = const IconData(0xe926, fontFamily: _kFontFam);
  static const IconData settings_power = const IconData(0xe929, fontFamily: _kFontFam);
  static const IconData settings_voice = const IconData(0xe928, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe92a, fontFamily: _kFontFam);
  static const IconData shield = const IconData(0xf132, fontFamily: _kFontFam);
  static const IconData shuffle = const IconData(0xe946, fontFamily: _kFontFam);
  static const IconData simplybuilt = const IconData(0xf215, fontFamily: _kFontFam);
  static const IconData skyatlas = const IconData(0xf216, fontFamily: _kFontFam);
  static const IconData skype = const IconData(0xf17e, fontFamily: _kFontFam);
  static const IconData slack = const IconData(0xf198, fontFamily: _kFontFam);
  static const IconData slideshare = const IconData(0xf1e7, fontFamily: _kFontFam);
  static const IconData slow_motion_video = const IconData(0xe92b, fontFamily: _kFontFam);
  static const IconData sort_down = const IconData(0xf0dd, fontFamily: _kFontFam);
  static const IconData sort_up = const IconData(0xf0de, fontFamily: _kFontFam);
  static const IconData spin1 = const IconData(0xe8ca, fontFamily: _kFontFam);
  static const IconData spin2 = const IconData(0xe8cb, fontFamily: _kFontFam);
  static const IconData spin3 = const IconData(0xe8c6, fontFamily: _kFontFam);
  static const IconData spin4 = const IconData(0xe8c7, fontFamily: _kFontFam);
  static const IconData spin6 = const IconData(0xe8cc, fontFamily: _kFontFam);
  static const IconData split = const IconData(0xe8f6, fontFamily: _kFontFam);
  static const IconData spoon = const IconData(0xf1b1, fontFamily: _kFontFam);
  static const IconData spotify = const IconData(0xf1bc, fontFamily: _kFontFam);
  static const IconData stay_current_landscape = const IconData(0xe8b4, fontFamily: _kFontFam);
  static const IconData stay_current_portrait = const IconData(0xe8b5, fontFamily: _kFontFam);
  static const IconData stop = const IconData(0xe919, fontFamily: _kFontFam);
  static const IconData stop_1 = const IconData(0xe94a, fontFamily: _kFontFam);
  static const IconData stop_circle = const IconData(0xf28d, fontFamily: _kFontFam);
  static const IconData stop_circle_o = const IconData(0xf28e, fontFamily: _kFontFam);
  static const IconData stop_circled = const IconData(0xe91a, fontFamily: _kFontFam);
  static const IconData style = const IconData(0xe92c, fontFamily: _kFontFam);
  static const IconData swap_horiz = const IconData(0xe92e, fontFamily: _kFontFam);
  static const IconData swap_vert = const IconData(0xe92d, fontFamily: _kFontFam);
  static const IconData switch_camera = const IconData(0xe8b6, fontFamily: _kFontFam);
  static const IconData switch_icon = const IconData(0xe948, fontFamily: _kFontFam);
  static const IconData switch_video = const IconData(0xe8b7, fontFamily: _kFontFam);
  static const IconData sync_disabled = const IconData(0xe8b8, fontFamily: _kFontFam);
  static const IconData sync_icon = const IconData(0xe8ba, fontFamily: _kFontFam);
  static const IconData sync_problem = const IconData(0xe8b9, fontFamily: _kFontFam);
  static const IconData system_update = const IconData(0xe8bb, fontFamily: _kFontFam);
  static const IconData system_update_alt = const IconData(0xe8bc, fontFamily: _kFontFam);
  static const IconData tab = const IconData(0xe8bd, fontFamily: _kFontFam);
  static const IconData tab_unselected = const IconData(0xe8be, fontFamily: _kFontFam);
  static const IconData tap_and_play = const IconData(0xe8bf, fontFamily: _kFontFam);
  static const IconData target = const IconData(0xe950, fontFamily: _kFontFam);
  static const IconData text_fields = const IconData(0xe8c2, fontFamily: _kFontFam);
  static const IconData thumb_down = const IconData(0xe8c0, fontFamily: _kFontFam);
  static const IconData thumb_up = const IconData(0xe8c1, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xe931, fontFamily: _kFontFam);
  static const IconData thumbs_down_1 = const IconData(0xe95e, fontFamily: _kFontFam);
  static const IconData thumbs_down_alt = const IconData(0xf165, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xe930, fontFamily: _kFontFam);
  static const IconData thumbs_up_1 = const IconData(0xe95d, fontFamily: _kFontFam);
  static const IconData thumbs_up_alt = const IconData(0xf164, fontFamily: _kFontFam);
  static const IconData toggle_off = const IconData(0xf204, fontFamily: _kFontFam);
  static const IconData toggle_on = const IconData(0xf205, fontFamily: _kFontFam);
  static const IconData translate = const IconData(0xe8c3, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe93b, fontFamily: _kFontFam);
  static const IconData trello = const IconData(0xf181, fontFamily: _kFontFam);
  static const IconData tumblr = const IconData(0xf173, fontFamily: _kFontFam);
  static const IconData tumblr_squared = const IconData(0xf174, fontFamily: _kFontFam);
  static const IconData twitter_1 = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData twitter_squared = const IconData(0xf304, fontFamily: _kFontFam);
  static const IconData ui_icon = const IconData(0xe906, fontFamily: _kFontFam);
  static const IconData unlink = const IconData(0xf127, fontFamily: _kFontFam);
  static const IconData up_circle = const IconData(0xe8fe, fontFamily: _kFontFam);
  static const IconData up_circle_1 = const IconData(0xe902, fontFamily: _kFontFam);
  static const IconData up_circled2 = const IconData(0xe8f0, fontFamily: _kFontFam);
  static const IconData up_dir = const IconData(0xe8ed, fontFamily: _kFontFam);
  static const IconData updown_circle = const IconData(0xe903, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe932, fontFamily: _kFontFam);
  static const IconData upload_cloud = const IconData(0xf0ee, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe8e2, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xf064, fontFamily: _kFontFam);
  static const IconData volume_down = const IconData(0xe8d7, fontFamily: _kFontFam);
  static const IconData volume_off = const IconData(0xe8d8, fontFamily: _kFontFam);
  static const IconData volume_up = const IconData(0xe8d6, fontFamily: _kFontFam);
  static const IconData webpack = const IconData(0xe8ea, fontFamily: _kFontFam);
  static const IconData wechat = const IconData(0xf1d7, fontFamily: _kFontFam);
  static const IconData wifi_tethering = const IconData(0xe8c5, fontFamily: _kFontFam);
  static const IconData wikipedia_w = const IconData(0xf266, fontFamily: _kFontFam);
  static const IconData windows = const IconData(0xe964, fontFamily: _kFontFam);
  static const IconData wordpress = const IconData(0xf19a, fontFamily: _kFontFam);
  static const IconData wrap_text = const IconData(0xe8c4, fontFamily: _kFontFam);
  static const IconData wrench = const IconData(0xe8d4, fontFamily: _kFontFam);
  static const IconData xing = const IconData(0xf168, fontFamily: _kFontFam);
  static const IconData youtube = const IconData(0xf167, fontFamily: _kFontFam);
  static const IconData youtube_play = const IconData(0xf16a, fontFamily: _kFontFam);
}
